// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5LxOTYoR0kuwbFBdYR-kfa77QaENT4bY',
    appId: '1:1027587774618:web:65a862a7078112b4256723',
    messagingSenderId: '1027587774618',
    projectId: 'urknight-a9821',
    authDomain: 'urknight-a9821.firebaseapp.com',
    storageBucket: 'urknight-a9821.firebasestorage.app',
    measurementId: 'G-GPWQ62BKV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi3ydUEnITQy0l64EssvHg8CKCCYcreLg',
    appId: '1:1027587774618:android:b609979729edd17f256723',
    messagingSenderId: '1027587774618',
    projectId: 'urknight-a9821',
    storageBucket: 'urknight-a9821.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-leuxm0RD80azsR9uKzoLIZ1pGyl-TjA',
    appId: '1:1027587774618:ios:d1cb39a7eb8dc76c256723',
    messagingSenderId: '1027587774618',
    projectId: 'urknight-a9821',
    storageBucket: 'urknight-a9821.firebasestorage.app',
    iosClientId: '1027587774618-8a6976lduprmfqlv0i3h8c848usg43h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.urknight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-leuxm0RD80azsR9uKzoLIZ1pGyl-TjA',
    appId: '1:1027587774618:ios:d1cb39a7eb8dc76c256723',
    messagingSenderId: '1027587774618',
    projectId: 'urknight-a9821',
    storageBucket: 'urknight-a9821.firebasestorage.app',
    iosClientId: '1027587774618-8a6976lduprmfqlv0i3h8c848usg43h8.apps.googleusercontent.com',
    iosBundleId: 'com.example.urknight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5LxOTYoR0kuwbFBdYR-kfa77QaENT4bY',
    appId: '1:1027587774618:web:3314416d8cc413fd256723',
    messagingSenderId: '1027587774618',
    projectId: 'urknight-a9821',
    authDomain: 'urknight-a9821.firebaseapp.com',
    storageBucket: 'urknight-a9821.firebasestorage.app',
    measurementId: 'G-41DM6LDYGW',
  );

}